name: 'Create Reminder'
author: 'UGRC'
description: 'Set a reminder when a comment is posted in an issue'
branding:
  icon: 'calendar'
  color: 'white'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  repoToken:
    description: 'github token'
    required: true
    default: '${{ github.token }}'
  repository:
    description: 'the repository name'
    required: true
    default: '${{ github.repository }}'
  repositoryOwner:
    description: 'the repository owner'
    required: true
    default: '${{ github.repository_owner }}'
